#!/usr/bin/env python

from smart_grasper import SmartGrasper

sgs = SmartGrasper()
# # Print object (standard_sphere_blue) pose
# sphere_blue_pose = sgs.get_object_pose()
# # Move tip to grab the sphere
# sgs.move_tip_absolute(sphere_blue_pose)
# # Send command
# # sgs.send_command({"H1_F1J1": -1.0, "shoulder_pan_joint": 1.0})
# sgs.open_hand()
# sgs.close_hand()
# sgs.check_fingers_collisions(True)
sgs.pick()